package com.circlenet.config;

import jakarta.servlet.*; import jakarta.servlet.http.*; import java.io.IOException; import java.time.Instant; import java.util.concurrent.ConcurrentHashMap; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.MediaType; import org.springframework.stereotype.Component; import org.springframework.web.filter.OncePerRequestFilter;
@Component public class RateLimitFilter extends OncePerRequestFilter{
 private final ConcurrentHashMap<String,Window> windows=new ConcurrentHashMap<>();
 private final int authLimit;private final int apiLimit;public RateLimitFilter(@Value("${circlenet.rate-limit.auth-per-minute:20}")int authLimit,@Value("${circlenet.rate-limit.api-per-minute:300}")int apiLimit){this.authLimit=authLimit;this.apiLimit=apiLimit;}
 @Override protected void doFilterInternal(HttpServletRequest request,HttpServletResponse response,FilterChain chain)throws ServletException,IOException{String path=request.getRequestURI();int limit=path.startsWith("/api/auth/")?authLimit:apiLimit;String ip=request.getHeader("X-Forwarded-For");if(ip==null)ip=request.getRemoteAddr();String key=ip.split(",")[0]+":"+(path.startsWith("/api/auth/")?"auth":"api");long minute=Instant.now().getEpochSecond()/60;Window window=windows.compute(key,(k,current)->current==null||current.minute!=minute?new Window(minute,1):new Window(minute,current.count+1));response.setHeader("X-RateLimit-Limit",String.valueOf(limit));response.setHeader("X-RateLimit-Remaining",String.valueOf(Math.max(0,limit-window.count)));if(window.count>limit){response.setStatus(429);response.setContentType(MediaType.APPLICATION_JSON_VALUE);response.getWriter().write("{\"message\":\"Too many requests. Please wait a minute and try again.\"}");return;}chain.doFilter(request,response);if(windows.size()>100000)windows.entrySet().removeIf(e->e.getValue().minute<minute-2);}
 private record Window(long minute,int count){}
}
