package com.circlenet.domain.moderation;
import com.circlenet.domain.user.UserRepository; import java.security.Principal; import java.time.Instant; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/moderation/reports") public class ModerationController{
 private static final Set<String> REASONS=Set.of("HARASSMENT","SPAM","IMPERSONATION","PRIVACY","ILLEGAL_CONTENT","OTHER"); private final AbuseReportRepository reports;private final UserRepository users;public ModerationController(AbuseReportRepository reports,UserRepository users){this.reports=reports;this.users=users;}
 @PostMapping public ReportDto create(Principal p,@RequestBody CreateReport r){String reason=r.reason()==null?"":r.reason().trim().toUpperCase();if(!REASONS.contains(reason))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Choose a valid report reason");if(r.reportedUserId()==null&&r.entityId()==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Choose a user or content to report");AbuseReportEntity e=new AbuseReportEntity();e.setReporterUserId(id(p));e.setReportedUserId(r.reportedUserId());e.setEntityType(clean(r.entityType()));e.setEntityId(r.entityId());e.setReason(reason);e.setDetails(limit(r.details(),2000));return dto(reports.save(e));}
 @GetMapping("/mine") public List<ReportDto> mine(Principal p){return reports.findByReporterUserIdOrderByCreatedAtDesc(id(p)).stream().map(this::dto).toList();}
 @GetMapping public List<ReportDto> list(Principal p){admin(p);return reports.findTop200ByOrderByCreatedAtDesc().stream().map(this::dto).toList();}
 @PutMapping("/{reportId}") public ReportDto moderate(Principal p,@PathVariable Long reportId,@RequestBody ModerateReport r){Long admin=admin(p);String status=r.status()==null?"":r.status().trim().toUpperCase();if(!Set.of("OPEN","REVIEWING","RESOLVED","DISMISSED").contains(status))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Choose a valid moderation status");var e=reports.findById(reportId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Report not found"));e.setStatus(status);e.setModeratorUserId(admin);e.setModeratorNotes(limit(r.notes(),2000));e.setUpdatedAt(Instant.now());return dto(reports.save(e));}
 private Long admin(Principal p){Long id=id(p);if(!"ADMIN".equals(users.findById(id).orElseThrow().getRole()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Administrator access required");return id;}private Long id(Principal p){return Long.valueOf(p.getName());}private String clean(String v){return v==null||v.isBlank()?null:v.trim().toUpperCase();}private String limit(String v,int max){return v==null?null:v.substring(0,Math.min(v.length(),max));}private ReportDto dto(AbuseReportEntity e){return new ReportDto(e.getId(),e.getReportedUserId(),e.getEntityType(),e.getEntityId(),e.getReason(),e.getDetails(),e.getStatus(),e.getModeratorNotes(),e.getCreatedAt(),e.getUpdatedAt());}
 public record CreateReport(Long reportedUserId,String entityType,Long entityId,String reason,String details){} public record ModerateReport(String status,String notes){} public record ReportDto(Long id,Long reportedUserId,String entityType,Long entityId,String reason,String details,String status,String moderatorNotes,Instant createdAt,Instant updatedAt){}
}
