ALTER TABLE circles ADD COLUMN IF NOT EXISTS posting_permission VARCHAR(32) NOT NULL DEFAULT 'ALL_MEMBERS';

CREATE TABLE IF NOT EXISTS circle_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  circle_id BIGINT NOT NULL,
  author_user_id BIGINT NOT NULL,
  parent_post_id BIGINT,
  message VARCHAR(4000) NOT NULL DEFAULT '',
  attachment_key VARCHAR(255),
  attachment_name VARCHAR(255),
  attachment_type VARCHAR(255),
  attachment_size BIGINT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_circle_post_circle FOREIGN KEY (circle_id) REFERENCES circles(id) ON DELETE CASCADE,
  CONSTRAINT fk_circle_post_author FOREIGN KEY (author_user_id) REFERENCES users(id),
  CONSTRAINT fk_circle_post_parent FOREIGN KEY (parent_post_id) REFERENCES circle_posts(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_circle_posts_circle_created ON circle_posts(circle_id,created_at);
