CREATE TABLE IF NOT EXISTS direct_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_user_id BIGINT NOT NULL,
  recipient_user_id BIGINT NOT NULL,
  message VARCHAR(4000) NOT NULL DEFAULT '',
  attachment_key VARCHAR(255),
  attachment_name VARCHAR(255),
  attachment_type VARCHAR(255),
  attachment_size BIGINT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_direct_message_sender FOREIGN KEY (sender_user_id) REFERENCES users(id),
  CONSTRAINT fk_direct_message_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(id),
  CONSTRAINT chk_direct_message_participants CHECK (sender_user_id <> recipient_user_id)
);

CREATE INDEX IF NOT EXISTS idx_direct_messages_participants_created
  ON direct_messages(sender_user_id, recipient_user_id, created_at);
