CREATE TABLE IF NOT EXISTS direct_calls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caller_user_id BIGINT NOT NULL,
  recipient_user_id BIGINT NOT NULL,
  call_type VARCHAR(16) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'RINGING',
  offer_sdp TEXT NOT NULL,
  answer_sdp TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_direct_call_caller FOREIGN KEY (caller_user_id) REFERENCES users(id),
  CONSTRAINT fk_direct_call_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(id),
  CONSTRAINT chk_direct_call_participants CHECK (caller_user_id <> recipient_user_id),
  CONSTRAINT chk_direct_call_type CHECK (call_type IN ('AUDIO','VIDEO')),
  CONSTRAINT chk_direct_call_status CHECK (status IN ('RINGING','ACCEPTED','REJECTED','ENDED'))
);
CREATE INDEX IF NOT EXISTS idx_direct_calls_recipient_status ON direct_calls(recipient_user_id,status,created_at);
