CREATE TABLE media_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id BIGINT NOT NULL,
  storage_key VARCHAR(700) NOT NULL UNIQUE,
  category VARCHAR(40) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  content_type VARCHAR(150) NOT NULL,
  size_bytes BIGINT NOT NULL,
  sha256 VARCHAR(64) NOT NULL,
  scan_status VARCHAR(24) NOT NULL DEFAULT 'CLEAN',
  thumbnail_key VARCHAR(700),
  expires_at TIMESTAMP,
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_media_asset_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT ck_media_asset_size CHECK (size_bytes >= 0)
);
CREATE INDEX idx_media_assets_owner_active ON media_assets(owner_user_id, deleted_at);
CREATE INDEX idx_media_assets_expiry ON media_assets(expires_at, deleted_at);
