CREATE TABLE audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT,
  action VARCHAR(20) NOT NULL,
  request_path VARCHAR(700) NOT NULL,
  resource_type VARCHAR(80),
  resource_id VARCHAR(120),
  response_status INTEGER NOT NULL,
  ip_address VARCHAR(64),
  user_agent VARCHAR(500),
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_actor_time ON audit_events(actor_user_id, occurred_at);
CREATE INDEX idx_audit_resource ON audit_events(resource_type, resource_id);

CREATE TABLE abuse_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_user_id BIGINT NOT NULL,
  reported_user_id BIGINT,
  entity_type VARCHAR(40),
  entity_id BIGINT,
  reason VARCHAR(40) NOT NULL,
  details VARCHAR(2000),
  status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
  moderator_user_id BIGINT,
  moderator_notes VARCHAR(2000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_abuse_reporter FOREIGN KEY (reporter_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_abuse_reported_user FOREIGN KEY (reported_user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_abuse_status_created ON abuse_reports(status, created_at);
