CREATE TABLE relationship_broadcasts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_user_id BIGINT NOT NULL,
  audience_type VARCHAR(24) NOT NULL,
  anchor_user_id BIGINT,
  location_query VARCHAR(255),
  message_preview VARCHAR(500),
  recipient_count INTEGER NOT NULL DEFAULT 0,
  failed_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_relationship_broadcast_sender FOREIGN KEY (sender_user_id) REFERENCES users(id),
  CONSTRAINT fk_relationship_broadcast_anchor FOREIGN KEY (anchor_user_id) REFERENCES users(id),
  CONSTRAINT chk_relationship_broadcast_audience CHECK (audience_type IN ('HORIZONTAL','VERTICAL','LOCATION'))
);

CREATE INDEX idx_relationship_broadcast_sender ON relationship_broadcasts(sender_user_id, created_at);
