CREATE TABLE social_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  caption VARCHAR(4000) NOT NULL DEFAULT '',
  audience VARCHAR(24) NOT NULL DEFAULT 'RELATIONSHIPS',
  circle_id BIGINT REFERENCES circles(id) ON DELETE CASCADE,
  media_key VARCHAR(255),
  media_name VARCHAR(255),
  media_type VARCHAR(255),
  media_size BIGINT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_social_post_audience CHECK (audience IN ('PUBLIC','RELATIONSHIPS','CIRCLE')),
  CONSTRAINT chk_social_post_circle CHECK ((audience = 'CIRCLE' AND circle_id IS NOT NULL) OR (audience <> 'CIRCLE' AND circle_id IS NULL))
);
CREATE INDEX idx_social_posts_created ON social_posts(created_at DESC);
CREATE INDEX idx_social_posts_author ON social_posts(author_user_id, created_at DESC);

CREATE TABLE social_post_likes (
  post_id BIGINT NOT NULL REFERENCES social_posts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (post_id, user_id)
);

CREATE TABLE social_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES social_posts(id) ON DELETE CASCADE,
  author_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message VARCHAR(1000) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_social_comments_post ON social_comments(post_id, created_at);

CREATE TABLE social_stories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  caption VARCHAR(1000) NOT NULL DEFAULT '',
  audience VARCHAR(24) NOT NULL DEFAULT 'RELATIONSHIPS',
  media_key VARCHAR(255) NOT NULL,
  media_name VARCHAR(255),
  media_type VARCHAR(255) NOT NULL,
  media_size BIGINT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT chk_social_story_audience CHECK (audience IN ('PUBLIC','RELATIONSHIPS'))
);
CREATE INDEX idx_social_stories_expiry ON social_stories(expires_at, created_at DESC);
