ALTER TABLE direct_messages ADD COLUMN reply_to_message_id BIGINT REFERENCES direct_messages(id) ON DELETE SET NULL;
ALTER TABLE direct_messages ADD COLUMN edited_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE direct_messages ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
CREATE INDEX idx_direct_messages_reply ON direct_messages(reply_to_message_id);

CREATE TABLE direct_message_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT NOT NULL REFERENCES direct_messages(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  emoji VARCHAR(16) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_direct_message_reaction UNIQUE(message_id,user_id)
);
CREATE INDEX idx_direct_message_reactions_message ON direct_message_reactions(message_id);
