CREATE TABLE circle_post_reads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES circle_posts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  read_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_circle_post_read UNIQUE(post_id,user_id)
);
CREATE INDEX idx_circle_post_reads_post ON circle_post_reads(post_id);
CREATE INDEX idx_circle_post_reads_user ON circle_post_reads(user_id);
