CREATE TABLE person_records (
  owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  person_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  nickname VARCHAR(255), contact_phone VARCHAR(40), contact_email VARCHAR(255),
  address TEXT, city VARCHAR(120), country VARCHAR(120), occupation VARCHAR(255),
  important_dates TEXT, notes TEXT, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (owner_user_id, person_user_id)
);

CREATE TABLE person_memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  person_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255), note TEXT, media_key VARCHAR(512), media_name VARCHAR(255),
  media_type VARCHAR(160), media_size BIGINT, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_person_memories_owner_person ON person_memories(owner_user_id, person_user_id, created_at DESC);
