CREATE TABLE IF NOT EXISTS auth_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token VARCHAR(2048) NOT NULL UNIQUE,
  user_id BIGINT,
  token_type VARCHAR(32) NOT NULL,
  expires_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_tokens_user_id ON auth_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_token_type ON auth_tokens(token_type);

ALTER TABLE auth_tokens
  ADD CONSTRAINT fk_auth_tokens_user
  FOREIGN KEY (user_id)
  REFERENCES users(id)
  ON DELETE CASCADE;
