'use client';

import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {AbuseReport,fetchModerationReports,fetchSessionProfile,hasAuthSession,isUnauthorizedError,updateModerationReport} from '../lib/api';

export default function ModerationPage(){
 const router=useRouter();const [reports,setReports]=useState<AbuseReport[]>([]);const [filter,setFilter]=useState('OPEN');const [message,setMessage]=useState('');const [busy,setBusy]=useState<number>();
 const load=useCallback(async()=>{try{const profile=await fetchSessionProfile();if(profile.role!=='ADMIN'){router.replace('/dashboard');return;}setReports(await fetchModerationReports());}catch(error){if(isUnauthorizedError(error))router.replace('/auth');else setMessage((error as Error).message);}},[router]);
 useEffect(()=>{if(!hasAuthSession())router.replace('/auth');else void load();},[load,router]);
 const update=async(report:AbuseReport,status:AbuseReport['status'])=>{const notes=window.prompt('Moderator notes',report.moderatorNotes||'')??report.moderatorNotes??'';setBusy(report.id);try{await updateModerationReport(report.id,status,notes);await load();setMessage(`Report #${report.id} updated.`);}catch(error){setMessage((error as Error).message);}finally{setBusy(undefined);}};
 const visible=filter==='ALL'?reports:reports.filter(report=>report.status===filter);
 return <main className="container moderation-page"><header className="network-header"><div><p className="eyebrow">TRUST & SAFETY</p><h1>Moderation queue</h1><p>Review user reports, document decisions, and close resolved cases.</p></div><Link href="/dashboard" className="btn btn-secondary">Dashboard</Link></header>{message&&<p className="network-message" role="status">{message}</p>}<nav className="moderation-filters">{['OPEN','REVIEWING','RESOLVED','DISMISSED','ALL'].map(value=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value.toLowerCase()} ({value==='ALL'?reports.length:reports.filter(item=>item.status===value).length})</button>)}</nav><section className="moderation-list">{visible.map(report=><article className="card" key={report.id}><header><span className={`moderation-status status-${report.status.toLowerCase()}`}>{report.status}</span><time>{new Date(report.createdAt).toLocaleString()}</time></header><h2>{report.reason.replaceAll('_',' ')}</h2><p>{report.details||'No additional details supplied.'}</p><dl><div><dt>Report</dt><dd>#{report.id}</dd></div><div><dt>Entity</dt><dd>{report.entityType||'Account'} {report.entityId?`#${report.entityId}`:''}</dd></div><div><dt>Reported user</dt><dd>{report.reportedUserId?`#${report.reportedUserId}`:'—'}</dd></div></dl>{report.moderatorNotes&&<blockquote>{report.moderatorNotes}</blockquote>}<footer><button disabled={busy===report.id} onClick={()=>void update(report,'REVIEWING')}>Reviewing</button><button disabled={busy===report.id} onClick={()=>void update(report,'RESOLVED')}>Resolve</button><button disabled={busy===report.id} onClick={()=>void update(report,'DISMISSED')}>Dismiss</button></footer></article>)}{!visible.length&&<div className="card social-empty"><h2>No {filter.toLowerCase()} reports</h2></div>}</section></main>;
}
